from fastapi import APIRouter, HTTPException
from app.schemas.models import AgentLaunchRequest
from app.agent.strategy_agent import StrategyAgent
from app.db.sqlite import get_latest_workspace, create_campaign_from_strategy

router = APIRouter(prefix="/agent", tags=["agent"])
strategy = StrategyAgent()

@router.post("/launch")
async def launch(payload: AgentLaunchRequest):
    # Resolve workspace
    ws = None
    if payload.workspace_id:
        ws = get_latest_workspace()
    else:
        ws = get_latest_workspace()

    if not ws:
        raise HTTPException(status_code=400, detail="No workspace found. Create workspace first.")

    offering = payload.offering
    icp = payload.icp

    positioning = await strategy.generate_positioning(offering, icp)
    messaging = await strategy.generate_messaging(offering, icp, positioning)
    sequence_plan = await strategy.generate_sequence(offering, icp, positioning, messaging)
    strategy_json = strategy.compose_campaign_strategy(offering, icp, positioning, messaging, sequence_plan)
    sequence_json = strategy.to_runner_sequence_json(sequence_plan)
    run_config_json = strategy.default_run_config()

    campaign_id = create_campaign_from_strategy(
        workspace_id=ws.id,
        name=sequence_plan.get("sequence_name") or "Autogenerated Campaign",
        strategy=strategy_json,
        sequence=sequence_json,
        run_config=run_config_json,
        status="running",
        cadence_days=3,
        max_touches=4,
    )

    return {
        "campaign_id": campaign_id,
        "status": "running",
        "summary": {
            "target_market": positioning.get("target_customer"),
            "value_prop": positioning.get("value_prop"),
            "themes": [t.get("name") for t in messaging.get("themes", [])][:3],
            "steps": [s.get("step_id") for s in sequence_plan.get("steps", [])],
        },
    }
